### ISSUE TITLE
[Lagg] Auto-Clicker problem

### ISSUE THREAD

**Issue by Lilli44** [mastercake10/TimeIsMoney#100]
Hello **mastercake10**,

we have a big problem, some users startet to using a auto-clicker on the deposite and withdraw buttons. - This produce laggs on our server. - Can you please add a little cooldown (of 1 second) between every press of the button? **It is very urgently and important!**

**Comment by LaurenceBarnes** [comment]
you should seriously punish these players in the first place, no tolerance imo.
but I do agree that this would be a decent addition.
