### ISSUE TITLE
Add a option for a second timer with a seperate reward

### ISSUE THREAD

**Issue by OzCNetwork** [mastercake10/TimeIsMoney#105]
### What steps will reproduce the issue?  
1. 
2. 
3. 

### What was supposed to happen?

>> A option in the config to add a secundairy timer besides the primary timer to reward players every 10min and every 60min with different rewards. Like every 10min 100 dollar ingame cash and every 60min ingame I would want to grant my players like  1-5 dirt blocks. 

Currently no issues, only this request.

Currently I can only have one timer with 1 or 2 rewards operational

### What version of TimeIsMoney are you using?  
The latest I think...?

**Comment by mastercake10** [comment]
duplicate #53
