### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Zomis** [mastercake10/TimeIsMoney#11]
As it currently stands, since you don't have any license no one is really allowed to do anything with your plugin. Please see these links:

https://help.github.com/articles/licensing-a-repository/
https://choosealicense.com/no-license/

Please add a license stating your intentions.

If you want the project to be free and open-source, I would personally recommend something like the MIT license or the Modified BSD license.

**Comment by mastercake10** [comment]
Thanks for informing me about this.
