### ISSUE TITLE
atm wont work

### ISSUE THREAD

**Issue by stuee147** [mastercake10/TimeIsMoney#17]
hi 
i love this plugin and have been using it on my server for sometime now but since the last update on the 5th aug no one has been able to use /atm or use the signs or even run threw a command block it still wont work can you help as i really like the atm feature and would like to be able to use them again 
thanks again for the great plugin
stuee147

**Comment by mastercake10** [comment]
Hey, have you tried to regenerate your config.yml?
I have done a few changes on the atm the last days and also added some configuration abilities to the config.yml, maybe these configuration abilities are not probably loaded.

**Comment by stuee147** [comment]
Hi
Thanks for the quick reply. Yes I have tried reloading the plugin and also done a few server restarts everything works great apart from the ATM I can't even access them it's a strange problem that has me confused lol.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mastercake10** [comment]
Does the issue still exist?
