### ISSUE TITLE
%money% contain more than the amount

### ISSUE THREAD

**Issue by seema84** [mastercake10/TimeIsMoney#26]
The placeholder %money% contain more than the amount.
With Fe Economy Plugin is the output "10 Fe". But my currency is not "Fe" thats only the Eco Plugin.
You need to change this for only the money amount.

Please add a Userblacklist (example for op players).

TimeIsMoney Version 1.9.6.3

**Comment by mastercake10** [comment]
Yeah, the %money% variable contains the formatted money string. The plugin works fine with well-known economy plugins like Essentials. Please ask the Author of your Economy plugin about this, and also link to this issue.

**Comment by seema84** [comment]
Fe Economy (https://www.spigotmc.org/resources/fe.723/) has stop the plugin support for a while. So i cant ask the Author.
Why do you use the full money string and not only the amount? Im pretty shure other Eco systems have the same problem.

**Comment by mastercake10** [comment]
Every currency has its currency symbol. So this is the reason why the amount has a currency symbol. Using most Economy plugins, the symbol can easily be removed.
