### ISSUE TITLE
It gives money 3-4 times every 10 minute

### ISSUE THREAD

**Issue by UnioDex** [mastercake10/TimeIsMoney#27]
Hello, i set TimeIsMoney to give $100.000 to each player every 10 minute. But it gives 2-3 even 4 times. 

TimeIsMoney version: 1.9.6.3
Config: https://pastebin.com/dz0smK3G
Logs: https://www.dropbox.com/s/nufgaxs5eoqzbou/log.zip?dl=0

In logs it says only once given but in game i have 4x money than $100.000.

I also tried to explain it with a GIF:  https://imgur.com/a/zDfE8bs

At first i have $0 but after it gives money it sends 3 message and $300.000. It supposed to send $100.000

### What Spigot version are you using? Paste the output of /version below.  
This server is running CraftBukkit version git-TacoSpigot-"c2835dfc" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  
zPermissions, PlugMan, NametagEdit, PandaWire, SimpleVIPPerks, UnioKredi, UnioServerMenu, UnioVagonSearcher, ViaVersion, CoreProtect, WorldEdit, WorldBorder, ProtocolLib, NoCheatPlus, UnioAntiGrief, MVdWPlaceholderAPI, React, FeatherBoard, ConditionalCommands, Vault, ObsidianAuctions, PlotSquared, WorldGuard, LockettePro, ChestCommands, WorldGuard_FlyStop, MyCommand, Essentials, UnioMarket, ChangeSkin, Jobs, UnioStatus, Multiverse-Core, TradeMe, EssentialsChat, TimeIsMoney, MineResetLite, SuperVanish, ChestShop, UnioAntiTradePaper, HolographicDisplays, Factions, MythicMobs, EssentialsProtect, EssentialsAntiBuild, EssentialsSpawn, ChatControl, CommandSigns, Plan, CustomHopper, CombatTagPlus, UnioFactions

### Are any errors related to TimeIsMoney in your console or logs? If so, paste below.  
No, but logs.txt full of Nulls in notepad++.

**Comment by mastercake10** [comment]
Have you tried running the Plugin on a Spigot-Server? There could be an issue with threading on this "Taco" build.

**Comment by UnioDex** [comment]
No, but there was no issue when i first install the plugin. It started to happen 2-3 days after. Also it still works fine my TacoSpigot test server. Seems like it is happening after players join the server.

**Comment by mastercake10** [comment]
I'll close this for now, since this does not seem to be an issue anymore.
