### ISSUE TITLE
AFK support plugins other than essentials

### ISSUE THREAD

**Issue by x1p** [mastercake10/TimeIsMoney#29]
TimeIsMoney currently supports only afk for essentials.
Is it possible to add support for CMI's afk state?

The AFK status can be read directly via CMI or via PlaceholderAPI/MVdWPlaceholderAPI from the placeholder `%cmi_user_afk%`

CMI is an alternative for essentials. More information at:
https://www.spigotmc.org/resources/cmi-240-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

**Comment by Scorpionvssub** [comment]
cmi also breaks a lot more things and often not even suggested alongside some plugins inc essentials

**Comment by x1p** [comment]
The real problem is that the afk mechanism of TimeIsMoney is far too basic.

**Comment by mastercake10** [comment]
> The real problem is that the afk mechanism of TimeIsMoney is far too basic.

I agree. That's the reason for the built-in essentials hook. We're definitely not going to hook into a premium plugin. Saying that the best solution would be enhancing the current afk mechanism of TIM.
