### ISSUE TITLE
1.14 Version?

### ISSUE THREAD

**Issue by Blueeyestar** [mastercake10/TimeIsMoney#32]
Hello, the TimeisMoney Plugin is just great :) We like to use it very much. Now we are slowly switching to 1.14 and wanted to ask carefully if there will also be a 1.14 version for the plugin ?

**Comment by Scorpionvssub** [comment]
Eventually.

Asking only delays the work we have to do on other versions.
1.14 isnt fully out yet with a ton bugs left both vanilla and spigot.

The discord has a FAQ that answers this too.
