### ISSUE TITLE
ERROR Could not pass event InventoryMoveItemEvent to TimeIsMoney v1.9.6.6 (1.14.2)

### ISSUE THREAD

**Issue by aurel85** [mastercake10/TimeIsMoney#39]
Hi,

I use PaperSpigot 1.14.2 and TimeIsMoney 1.9.6.6.

TimeIsMoney spamming the server with this : 

https://pastebin.com/wXsyevhN

**Comment by Blueeyestar** [comment]
https://github.com/mastercake10/TimeIsMoney/issues/38

**Comment by aurel85** [comment]
Oh, sorry for the duplicate topic.
