### ISSUE TITLE
Missing API version - PaperMC 199 MC 1.14.4

### ISSUE THREAD

**Issue by Possemaster** [mastercake10/TimeIsMoney#42]
### What steps will reproduce the issue?  
1. Install latest plugin
2. start server

### What was supposed to happen?
Clean Console

### What happened instead? 
[WARNING] .... Plugin TimeIsMoney v1.9.6.10 does not specify an api-version.

### What version of TimeIsMoney are you using?  
v1.9.6.10

### What Spigot version are you using? Paste the output of /version below.  
PaperMC 199

### What plugins do you have installed? Paste the output of /plugins below.  
N/A

### Are any errors related to TimeIsMoney in your console or logs? If so, paste below.  
```
[WARNING] .... Plugin TimeIsMoney v1.9.6.10 does not specify an api-version.
```
### Any additional information that you would like to provide that may be relevant to the issue?
Nope, just A Server Admin QOL fix

**Comment by mastercake10** [comment]
I've removed the api version again in 183f5c8 since it does not serve any purpose. We're not going to use 1.13+ materials and want to keep up legacy support. I don't know why this warning comes up on spigot although it is obvious that the plugin is coded on a legacy version.
