### ISSUE TITLE
bug, or rather a flaw

### ISSUE THREAD

**Issue by mrdeniska1234** [mastercake10/TimeIsMoney#44]
If there is a limit on the amount of currency, then when withdrawing money through an ATM, money simply disappears

Please fix it.

**Comment by mastercake10** [comment]
Thanks for submitting your issue.
Can you provide more details on this? Please use the issue template next time
https://github.com/mastercake10/TimeIsMoney/blob/master/ISSUE_TEMPLATE.md

**Comment by mrdeniska1234** [comment]
through essentials there is a money limit that a player may have at $ 100,000. If the player has 100,000 in his hands, then when they withdraw money from the ATM, they disappear. There is not enough verification whether it is possible to give the player money or not.

**Comment by mrdeniska1234** [comment]
I check update, my problem not fixed ((

**Comment by mastercake10** [comment]
> I check update, my problem not fixed ((

How's that? I've added a message which says that you can't withdraw money when you don't have enough money left in your atm...

**Comment by mrdeniska1234** [comment]
That was not the problem. Sorry for my English, and the result is a misunderstanding.
In Essentials there is a player’s money limit, say 100,000. If a player already has 100,000 in his hands, then when they withdraw money from an ATM, they simply burn from the account at the ATM

**Comment by mrdeniska1234** [comment]
https://youtu.be/N4GA5tDO9-s

**Comment by mastercake10** [comment]
After looking a bit into Vault and EssentialsX, I've found out that this issue is not relevant to TimeIsMoney.

Please see https://github.com/MilkBowl/Vault/issues/805 for further updates.
