### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by falget** [mastercake10/TimeIsMoney#5]
CraftBukkit version git-Spigot-72c2605-709783c (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
Latest TimeIsMoney

http://pastebin.com/XxEPm3Jy

**Comment by mastercake10** [comment]
You made an error in the config.yml.

**Comment by mastercake10** [comment]
* Update-Server is currently down, sorry for that. Will be back soon.

**Comment by Darlelet** [comment]
Is your webserver OK? Cause it seems to just read php files instead of executing them as it would normally do: http://avendria.de/tim/checkversion.php. You should take a look at your PHP installation 😉.

**Comment by mastercake10** [comment]
Thank you for reporting, that was pretty weird. I was upgrading my kernel, but a reinstallation of PHP fixed that

**Comment by Darlelet** [comment]
No problem, glad you fixed it. Update task won't be crashing anymore :)
