### ISSUE TITLE
Feature Request: Payout Logging

### ISSUE THREAD

**Issue by univerme** [mastercake10/TimeIsMoney#51]
Is there a way were all the online time payouts could be logged so we would know how much money is actually being added. This would be great as we are currently trying to measure how much money goes in and out. Additionally, would it be possible for all the payouts to come from a central account?

**Comment by mastercake10** [comment]
> Is there a way were all the online time payouts could be logged so we would know how much money is actually being added. This would be great as we are currently trying to measure how much money goes in and out.

This is already implemented. Enable `debug-log` in your config.yml for logging all payouts. (https://github.com/mastercake10/TimeIsMoney/blob/master/Plugin/src/main/resources/config.yml#L3)
The plugin will log all payouts in the log.txt file then. 

> Additionally, would it be possible for all the payouts to come from a central account?

This is not possible yet, please create a seperated feature request for this.
