### ISSUE TITLE
Feature Request: Add PlaceholderAPI

### ISSUE THREAD

**Issue by DerpsDer** [mastercake10/TimeIsMoney#54]
Hey, so i've been using this plugin for a bit and found out it has no Placeholders, If it had some it'd be very useful such as in custom GUIs to check a user's bank balance without going to an ATM, Or to make some sort of leaderboard for the person that has gotten the most balance in their playtime from Time Is Money plugin, i plan on using it in  custom GUI using math placeholders to get the user's total balance [Time Is Money bank balance + Vault Eco Balance] I think this would be a great feature to add for servers to use, if this is added please notify me on discord [DerpsDer#6034], thank.

**Comment by mastercake10** [comment]
Use `%tim_atm%` as placeholder in the newest release (see release tab for a dev version)
