### ISSUE TITLE
Option to stop the payout limit message after the first time it caps.

### ISSUE THREAD

**Issue by xNinjaKittyx** [mastercake10/TimeIsMoney#59]
Hi, I would like to have an option to stop printing the limit payout messasge after it caps for the first time.

Can sometimes get annoying to users to have the message repeatedly printing.

Minecraft version: 1.15.2 using SpigotMC
TimeIsMoney version 1.9.6.11

**Comment by mastercake10** [comment]
added in b71749fc074b34bfcaae688076f9201b5cb9959a
