### ISSUE TITLE
No colors

### ISSUE THREAD

**Issue by AlexNova1555** [mastercake10/TimeIsMoney#6]
so after i have updated my plugin to the newest version the plugin color are not working any more..
i getting no errors
i'm using spigot:   git-Spigot-de459a2-51263e9 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

TimeisMoney: 1.9.4.5

and here what its looks like the color codes:
http://prnt.sc/eaqzv5
http://prnt.sc/eaqzxt
http://prnt.sc/eaqzzs

**Comment by mastercake10** [comment]
please try to delete your config.yml and let the plugin generate a new one.

**Comment by mastercake10** [comment]
Edit: It's an error in the plugin. Next update will fix it.
