### ISSUE TITLE
Give Diamond Command Removed But Still Happening After Restart

### ISSUE THREAD

**Issue by firrae** [mastercake10/TimeIsMoney#60]
### What steps will reproduce the issue?  
1. Fresh PaperCraft server
2. Install Vault, EssentialsX, TIM
3. Remove command to give diamonds to VIPs

### What was supposed to happen?
When I removed the command I expected to restart the server and have it no longer give diamonds to VIPs.

### What happened instead? 
VIPs still get money. The amount of money which I changed is correct though.

### What version of TimeIsMoney are you using?  
1.9.6.12

### What Spigot version are you using? Paste the output of /version below.  
PaperCraft: `You are running the latest version`

### What plugins do you have installed? Paste the output of /plugins below.  
`DiscordSRV, dynmap*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, LuckPerms, TimeIsMoney*, Vault`

### Are any errors related to TimeIsMoney in your console or logs? If so, paste below.  
No, just the log of it giving people the diamond.

### Any additional information that you would like to provide that may be relevant to the issue?
I'm honestly just confused if I did something wrong? I've used TIM on other servers but this is the only one with the latest version and the only one this has happened on.

**Comment by Zippyduda** [comment]
I can confirm this issue as can The Omen from the Discord. Happens if you comment out the command line itself and happens if you comment out "commands:" in the config: https://pastebin.com/F2n1MPwe

**Comment by firrae** [comment]
Awesome, thanks @mastercake10!
