### ISSUE TITLE
Balancetop function isn't working...

### ISSUE THREAD

**Issue by Lilith8882** [mastercake10/TimeIsMoney#62]
I've found a bug on "1.9.6.12-fix":

The balancetop function isn't working on my 1.12.2 server, if I enter this command it show me a list of the 10 alphabetical sorted user, but not sorted to balances.

**Comment by Lilith8882** [comment]
Will there still be a bug fix for this function, because otherwise it is unfortunately completely unusable? - Because the sorting of the 10 users does absolutely nothing if it does not correspond to the totals?

**Comment by mastercake10** [comment]
Yes, I'll fix this when I get the chance to.
