### ISSUE TITLE
Add option to only pay 1 IP ADDRESS at the same time

### ISSUE THREAD

**Issue by soluciones-ya** [mastercake10/TimeIsMoney#7]
Some of my players are using multiple accounts (SAME IP ADDRESS) to abuse the payment every X minutes.

Could you add something to prevent this?

**Comment by mastercake10** [comment]
Updated. Just change the line allow-multiple-accounts: true to allow-multiple-accounts: false in your [config.yml](https://github.com/mastercake10/TimeIsMoney/blob/master/TimeIsMoney2/src/config.yml)
