### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by soluciones-ya** [mastercake10/TimeIsMoney#8]
The Player object you're using in the HashMaps are not removed when the player leaves the server

This is causing a memory leak in my server

From a recently dump:
https://i.gyazo.com/0e4425cabf8fc5e151601737111b8205.png

**Comment by mastercake10** [comment]
Thank you, the new update may fix this issue, let me know.

**Comment by mastercake10** [comment]
I think this issue has been solved.
