### ISSUE TITLE
Players without permission can build ATMs [CRIT BUG]

### ISSUE THREAD

**Issue by CloudeLecaw** [mastercake10/TimeIsMoney#80]
realted to my old one #79 

![](https://cdn.discordapp.com/attachments/725398308557815890/747721372486205480/Snag_12a9a6.png)
now you get the meassge you cant build ATM

but the atm still is build

Maybe the sign shoud drope or breake when you dont have the permission so player can pickup the sign and walk "away"

at the moment the ATM is still created and also works after
![Snag_19b5c9](https://user-images.githubusercontent.com/12080017/91146822-b4815580-e6b7-11ea-9406-db4a2ee6da6c.png)

**Comment by mastercake10** [comment]
I've uploaded the new jar file under the same version tag.
