### ISSUE TITLE
[BUG] Balancetop function is broke and debug infos are showing

### ISSUE THREAD

**Issue by MyTimeIsMoney** [mastercake10/TimeIsMoney#82]
Hello mastercake10,

I have tested the _second version of 1.9.6.16_ and I found 2 last bugs.

The first one is the **balancetop function**, this shows "UUID_TimBANK: value", can you please fix this, that it shows the Username instead the UUID, because I don't know which user is behind this entry.

The second is, If a user haven't permission to create atm signs **it shows debug infos in chat and console**, it show "WALL_SIGN" and "SIGN_POST", please fix it, too.

All other is working fine at the moment... :)

**Comment by mastercake10** [comment]
sorry for the poor fixes, I hope the new update (uploaded it under the same version tag again) will finally fix the issues.

**Comment by MyTimeIsMoney** [comment]
Yes, I've tried it out, this 2 bugs are **fixed** now. - _I close it!_ ;)
