### ISSUE TITLE
[Improvement] Formatting the amount of money from /atm balance <Username>

### ISSUE THREAD

**Issue by MyTimeIsMoney** [mastercake10/TimeIsMoney#84]
I still have a suggestion for improvement, would it be possible to display the amount of money in the same way as with the /atm balancetop? - For example, the balancetop function show it 1.250,00 and the balance function only 1250.00 - It would be nice to do it like balancetop in balance, because this is better to read...

**Comment by Antje2005** [comment]
Ich habe gerade mal bei mir geschaut, ich kann es auch bestätigen das die Beträge in zwei verschiedenen Formatierungen angezeigt werden.
