### ISSUE TITLE
[Improvement] 2 little mistakes in help...

### ISSUE THREAD

**Issue by MyTimeIsMoney** [mastercake10/TimeIsMoney#85]
I found 2 little mistakes in the help:

`/atm give <player> [world] - Deposits money into a players atm`
`/atm take <player> [world] - Withdraws money from a players atm`

**I think it should be looks like:**

`/atm give <player> <amount> [world] - Deposits money into a players atm`
`/atm take <player> <amount> [world] - Withdraws money from a players atm`

**Comment by MyTimeIsMoney** [comment]
Sorry for the 3 new entries here on GitHub, but I was testing all things in this plugin and this is all what I have seen (tested on a Spigot 1.12.2 server). ;)

**Comment by Antje2005** [comment]
... und ja, dieses <amount> fehlt da wirklich...

**Comment by WarenGonzaga** [comment]
Is anyone working on this?
