### ISSUE TITLE
[Enhancement] Second placeholder with other kind of formatting

### ISSUE THREAD

**Issue by MyTimeIsMoney** [mastercake10/TimeIsMoney#86]
Can you please integrate a second placeholder?

At the moment the placeholder is showing the amount in this format "$1.500,00", can you add a second with showing the amount in this format "$1500"?

**Comment by MyTimeIsMoney** [comment]
... or can you integrate a config value which give the option to define a own formatting ?

**Comment by MyTimeIsMoney** [comment]
I hope you can do that, it's very important for us, for integrate your plugin completely on our server.

**Comment by MyTimeIsMoney** [comment]
Finally, WEEKEND! :) - Can you please add this function now? - Can't wait, because to do the last step for integrate you plugin.

**Comment by mastercake10** [comment]
The money formatting thing doesn't happen on the TimeIsMoney side. Your economy plugin is solely responsible for the resulting "money string".

**Comment by MyTimeIsMoney** [comment]
But this improvement request show your plugin can do this: [#84 ](https://github.com/mastercake10/TimeIsMoney/issues/84)

**Comment by MyTimeIsMoney** [comment]
Or can you put in a solution like this for your plugin? -> [PlaceholderAPI - Vault ](https://api.extendedclip.com/expansions/vault/)

**Comment by MyTimeIsMoney** [comment]
The problem is, for technical reasons my scoreboard show the amount of Vault with PlaceholderAPI only in this formatting, under this amount I like to integrate the amount of TIM, too, but it looks ugly when both amounts have different formattings... :(

**Comment by mastercake10** [comment]
> Or can you put in a solution like this for your plugin? -> [PlaceholderAPI - Vault ](https://api.extendedclip.com/expansions/vault/)

Vault on its own is only an API for managing transactions, thus you always need an economy plugin on top of that which suits your needs. The economy plugin lets you define a formatting string, so that the Vault-API would always return the same formatted money string to all plugins. I don't really understand the function of these placeholders for the "vault expansion", but my guess is that ` %vault_eco_balance_formatted%` would return the same formatting like my plugin do. I don't really know why the "vault expansion" supports multiple formats, while the formatting should always be done using an economy plugin.



> The problem is, for technical reasons my scoreboard show the amount of Vault with PlaceholderAPI only in this formatting, under this amount I like to integrate the amount of TIM, too, but it looks ugly when both amounts have different formattings... :(

If that's really the case, tell the author of this plugin to require the formatting string using the VaultAPI, not creating a new one.

**Comment by MyTimeIsMoney** [comment]
The author have written the plugin for us long time ago and they don't support it anymore, but this is linked with many other things on our server, thats why we can't change it. - Please, can you help us with a alternative solution that we can fit you plugin in our server, too... Please! :(

**Comment by MyTimeIsMoney** [comment]
Btw. we use EssentialsX with Vault and integrate the amount in the scoreboard with this PlaceholderAPI extension.

**Comment by MyTimeIsMoney** [comment]
Can you help us? - We don't know how we can do that without your help... I'm not a developer... :(

**Comment by MyTimeIsMoney** [comment]
It would be good, if you only add a second placeholder with the same amount display like you done it with the function /atm balance <user> (if it's a bug, then we need this bug as an feature into a placeholder) :)

**Comment by Antje2005** [comment]
Hallo, ich habe gerade dieses Ticket hier entdeckt und ich bräuchte auch so eine Funktion, ich hoffe jemand versteht mich, da mein Englisch sehr schlecht ist, lesen kann ich es, aber mir selbst schreiben ist schlecht... ich hoffe der Plugin-Autor kann zufällig auch Deutsch sprechen...

**Comment by MyTimeIsMoney** [comment]
Do you can't help us? - That's to cry... we can't integrate it without your help... on many examples like the PlaceholderAPI of Vault and the "bug" into your /atm balance user function we can see it exist a way to doing that, but you don't help us... you're a developer, we are only administrators... we need you help! :(

**Comment by mastercake10** [comment]
I have no obligation on adding an option for formatting the money string via TimeIsMoney.

You're basically trying to fix a problem that originally arose from one of your plugins which doesn't seem to use the VaultAPI to format the money. Implementing a money label in TimeIsMoney doesn't fix your issue.

I suggest finding a developer that is willing to fix your problem.
