### ISSUE TITLE
 [Server thread/ERROR]: Could not pass event MagicSpellsEntityDamageByEntityEvent to MMOItems v4.7.3 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by TanoBrothers** [mastercake10/TimeIsMoney#97]
Does someone know how to solve this issue? 

 [Server thread/ERROR]: Could not pass event MagicSpellsEntityDamageByEntityEvent to MMOItems v4.7.3
org.bukkit.event.EventException: null

**Comment by mastercake10** [comment]
Not relevant for TimeIsMoney (it says MMOItem)
